MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Models/AddCollege.cs
namespace MyCollegeMVC.Models
{
    public class AddCollege
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Models/College.cs
namespace MyCollegeMVC.Models
{
    public class College
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Models/Department.cs
namespace MyCollegeMVC.Models
{
    public class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Models/ErrorViewModel.cs
namespace MyCollegeMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Models/UpdateCollege.cs
namespace MyCollegeMVC.Models
{
    public class UpdateCollege
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }

}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Controllers/CollegeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MyCollegeMVC.Data;
using MyCollegeMVC.Models;

namespace MyCollegeMVC.Controllers
{
    public class CollegeController : Controller
    {
        //static IList<College> CollegeList = new List<College>
        //{
        //new College() { Id = 1, Name = "Poornima", Type = "Private" }
        //};

        private readonly CollegeDbContext collegeDbContext;

        public CollegeController(CollegeDbContext collegeDbContext)
        {
            this.collegeDbContext = collegeDbContext;
        }


        public IActionResult Index()

        {
            //List<College> list = new List<College>();
            //College college = new College();
            //college.Name = "Poornima";
            //college.Type = "Private";
            //college.Id = 1;
            //list.Add(college);
           // return View(collegeDbContext.CollegeData.ToList());
            return View(collegeDbContext.CollegeData.FromSqlRaw("Getallcollege").ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AddCollege addCollege)
        {
            var college = new College()
            {
                Id = addCollege.Id,
                Name = addCollege.Name,
                Type = addCollege.Type
            };
            await collegeDbContext.CollegeData.AddAsync(college);
            await collegeDbContext.SaveChangesAsync();
            //studentList.Add(student);
            return RedirectToAction("Index");
        }

        //[HttpGet]
        //public ActionResult Edit(int Id)
        //{

        //    var college = collegeDbContext.CollegeData.Where(s => s.Id == Id).FirstOrDefault();

        //    // update student to the database

        //    return View(college);
        //}
        //[HttpPost]
        //public async Task<IActionResult> Edit(UpdateCollege update)
        //{
        //    //update student in DB using EntityFramodel ework in real-life application

        //    //update list by remodel oving old student and adding updated student for demodel o purpose
        //    var college = await collegeDbContext.CollegeData.FindAsync(update.Id);
        //    if (college!= null)
        //    {
        //        college.Name = update.Name;
        //        college.Type = update.Type;
        //        await collegeDbContext.SaveChangesAsync();
        //    }
        //    return RedirectToAction("Index");
        //    // var student = studentDbContext.StudentInformation.Where(s => s.Id == update.Id).FirstOrDefault();
        //    //studentDbContext.StudentInformation.Remove(student);
        //    //studentDbContext.StudentInformation.Add(update);


        //}

//---------------------------------------------------------------------------------------------------------
        
        //[HttpGet]
        //public async Task<ActionResult> Edit(int Id)
        //{
        //    //here, get the student from the database in the real application

        //    //getting a student from collection for demo purpose
        //    //var std = shopList.Where(s => s.ProductId == ProductId).FirstOrDefault();
        //    var college = await collegeDbContext.CollegeData.FirstOrDefaultAsync(s => s.Id == Id);
        //    if (college != null)
        //    {
        //        var college1 = new UpdateCollege()
        //        {
        //            Id = college.Id,
        //            Name = college.Name,
        //            Type = college.Type,
        //        };
        //        return View(college1);
        //    }
        //    return RedirectToAction("Index");

        //}

        //[HttpPost]
        //public async Task<IActionResult> Edit(UpdateCollege update)

        //{

        //    var college = await collegeDbContext.CollegeData.FindAsync(update.Id);
        //    if (college != null)
        //    {
        //        college.Id = update.Id;
        //        college.Type = update.Type;
        //        college.Name = update.Name;


        //        await collegeDbContext.SaveChangesAsync();

        //    }
        //    return RedirectToAction("Index");
        //}
        
        public IActionResult Edit(int Id)
        {
            return View(collegeDbContext.CollegeData.FromSqlRaw($"Getsinglecollege {Id}").AsEnumerable().FirstOrDefault());
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, string Name)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter()
                {
                    ParameterName = "@Name",
                    SqlDbType=System.Data.SqlDbType.VarChar,
                    Value=Name
                },
                new SqlParameter()
                {
                    ParameterName = "@Id",
                    SqlDbType=System.Data.SqlDbType.Int,
                    Value=Id
                }
            };

            var Updatecollege = await collegeDbContext.Database.ExecuteSqlRawAsync($"Exec Updatecollege @Id, @Name", param);
            if(Updatecollege == 1)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Details(College clg)
        {
            var college = collegeDbContext.CollegeData.Where(s => s.Id == clg.Id).First();
            return View(college);
        }

        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var college = await collegeDbContext.CollegeData.FirstAsync(s => s.Id == Id);
            if (college == null)
            {
                return NotFound();
            }

            return View(college);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            var college = await collegeDbContext.CollegeData.FindAsync(Id);
            {

                collegeDbContext.CollegeData.Remove(college);
                await collegeDbContext.SaveChangesAsync();

            }
            return RedirectToAction("Index");
            //var student = studentDbContext.StudentInformation.Where(s => s.Id == Id).First();
            //studentDbContext.StudentInformation.Remove(student);
            //return RedirectToAction("Index");
        }

        public ActionResult Get()
        {
            return View(collegeDbContext.DepartmentData.ToList());
        }
    }
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCollegeMVC.Models;
using System.Diagnostics;

namespace MyCollegeMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Create.cshtml
@model MyCollegeMVC.Models.AddCollege

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>AddCollege</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Delete.cshtml
@model MyCollegeMVC.Models.College

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>College</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Details.cshtml
@model MyCollegeMVC.Models.College

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>College</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Edit.cshtml
@model MyCollegeMVC.Models.College
@*@model MyCollegeMVC.Models.UpdateCollege*@

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>UpdateCollege</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Get.cshtml
@model IEnumerable<MyCollegeMVC.Models.Department>

@{
    ViewData["Title"] = "Get";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Get</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/College/Index.cshtml
@model IEnumerable<MyCollegeMVC.Models.College>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @*<a href="@Url.Action("Edit",new {item.Id})">Edit</a> |*@
                    <a href="@Url.Action("Details",new {item.Id})">Details</a> |
                    <a href="@Url.Action("Delete",new {item.Id})">Delete</a> |
                    <a href="@Url.Action("Edit",new {item.Id})">Edit</a> |
@*                    @Html.ActionLink("Edit", "Edit", new { item.Id }) |*@
                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>
</table>

MyCollegeMVC/MyCollegeMVC/MyCollegeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCollegeMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCollegeMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyCollegeMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="College" asp-action="Index">College</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="College" asp-action="Get">Department</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyCollegeMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>